#!/usr/bin/env bash

cat \
openajax_a11y_constants.js \
wai_aria/aria.js \
scripts/cache_util.js \
scripts/cache_abbreviations.js \
scripts/cache_color_contrast.js \
scripts/cache_controls.js \
scripts/cache_dom_element.js \
scripts/cache_dom_traversal.js \
scripts/cache_headings_landmarks.js \
scripts/cache_images.js \
scripts/cache_languages.js \
scripts/cache_links.js \
scripts/cache_lists.js \
scripts/cache_media.js \
scripts/cache_style.js \
scripts/cache_tables.js \
scripts/cache_title_main.js \
scripts/rules.js \
scripts/rule_results.js \
scripts/cache_nls.js \
scripts/wcag20_nls.js \
scripts/wcag20_results.js \
scripts/wcag20_ruleset.js \
scripts/progress_log.js \
openajax_a11y.js \
nls/cache_nls_en-us.js \
nls/rules_nls_en-us.js \
nls/wcag20_nls_en-us.js \
rules/rules_color_contrast.js \
rules/rules_controls.js \
rules/rules_images.js \
rulesets/wcag20_aria_transitional_ruleset.js \
rulesets/wcag20_aria_strict_ruleset.js > openajax_a11y_all.js

