  <body>
    
    <div>
      <div role="banner">
        <h1 id="ID_H1_TITLE"></h1>
      </div>
      <div role="navigation">
        <h2 id="ID_H2_MAIN_NAV"></h2>  
        <ul>
          <li><a href="#ID_A_ELEMENT_SUMMARY">Element Summary</a></li>
          <li>Rule Summary</li>
          <li><a href="#ID_DIV_CSV">CSV for Spreadsheet Export</a></li>
        </ul>
      </div>
      
      <div role="main" aria-labelledby="ID_H1_ELEMENT_SUMMARY">
        <h1 id="ID_H1_ELEMENT_SUMMARY"><a id="ID_A_ELEMENT_SUMMARY" name="ID_A_ELEMENT_SUMMARY"></a>Evaluation Summary</h1>
        <p>Summary of the types of evaluation results for each element</p>
        
        <table id="ID_TABLE_ELEMENT_SUMMARY" summary="Summary of the types of evaluation results for each element">
          <thead>
            <th class="order">Order</th>
            <th class="element">Element</th>
            <th class="hidden">Hidden</th>
            <th class="passed">Passed</th>
            <th class="warning">Warnings</th>
            <th class="manual_check">Manual Checks</th>
            <th class="violation">Violations</th>
          </thead>
          <tbody id="ID_TBODY_ELEMENT_SUMMARY">
            
          </tbody>
        </table>
      </div>

      <div id="ID_DIV_ELEMENT_DETAILS" role="region" aria-labelledby="ID_H2_ELEMENT_DETAILS">
        <h2 id="ID_H2_ELEMENT_DETAILS">Evaluation Result Details</h2>
        

        
      </div>

      <div id="ID_DIV_CSV" role="region" aria-labelledby="ID_H2_CSV">
        <h2 id="ID_H2_CSV">Evaluation Result CSV Format</h2>
        
        <pre id="ID_PRE_CSV">
          
        </pre>
        
      </div>
      
    </div>  
    
  </body>
