  <body>
    
      <div role="main" aria-labelledby="ID_H1_TITLE">
        <h1 id="ID_H1_TITLE"></h1>
        <p style="display: none"><a href="report_rule_summary.csv">CSV Export of Rule Summary Results</a></p>
        
        <table id="ID_TABLE_SUMMARY">
          <thead>
            <tr>
              <th>Summary Item</th>
              <th>Required</th>
              <th><abbr title="Web Content Accessibility Guidelines">WCAG</abbr> 2.0<br/>Level</th>
              <th><abbr titel="Percentage of Elements Pass Rule">PEPR</abbr></th>
              <th><abbr title="Manual Checks">MC</abbr></th>
              <th>Average <br/><abbr titel="Percentage of Elements Pass Rule">PEPR</abbr></th>
              <th>Total <abbr title="Manual Checks">MC</abbr></th>
            </tr>
          </thead>
          <tbody id="ID_TBODY_SUMMARY">
          </tbody>
        </table>
       
      </div> 
  </body>
