  <body>
    
      <div role="main" aria-labelledby="ID_H1_TITLE">
        <h1 id="ID_H1_TITLE"></h1>
        
        <div role="region" aria-labelledby="ID_H2_EVAL_INFO">
          <h2 id="ID_H2_EVAL_INFO">Evaluation Information</h2>
          <div class="info"><span class="label">Title: </span>  <span class="item" id="ID_SPAN_EVAL_TITLE"></span></div>
          <div class="info"><span class="label">URL: </span>    <span class="item"><a id="ID_A_EVAL_URL"></a></span></div>
          <div class="info"><span class="label">Date: </span>   <span class="item" id="ID_SPAN_EVAL_DATE"></span></div>
          <div class="info"><span class="label">Ruleset: </span><span class="item"><span id="ID_SPAN_RULESET_TITLE"></span> (<span id="ID_SPAN_RULESET_VERSION"></span>)</span></div>

<!--
          <div class="csv"><a href="report_rule_summary.csv">CSV Export of Rule Category Results</a></div>
-->          
        </div>   
       
        <div role="region" aria-labelledby="ID_H2_SUMMARY">
          <h2 id="ID_H2_SUMMARY">Rule Category Summary</h2>
          
          <p>Summary of rule results for each rule in the rule category.</p>
          
          <table id="ID_TABLE_SUMMARY" summary="">
            <thead>
              <tr>
                <th class="rule">Rule</th>
                <th class="description">Description</th>
                <th class="required">Required</th>
                <th class="wcag20_level"><abbr title="WCAG 2.0 Level">Level</abbr></th>
                <th class="pepr"><abbr title="Percentage of Elements Passing Rule">PEPR</abbr></th>
                <th class="mc">Manual Checks</th>
                <th class="v">Violations</th>
                <th class="w">Warnings</th>
                <th class="p">Pass</th>
                <th class="h">Hidden</th>
              </tr>
            </thead>
            <tbody id="ID_TBODY_SUMMARY">

            </tbody>
          </table>
        </div>
        <div role="region" aria-labelledby="ID_H2_DETAILS">
          <h2 id="ID_H2_DETAILS">Rule Category Details</h2>
          <p><em>not implemented at this time</em></p>
        </div>  
      </div> 
  </body>
