#!/usr/bin/env bash

rm -R ../api_docs/*.html
jsdoc -d ../api_docs            \
openajax_a11y_constants.js      \
openajax_a11y.js                \
scripts/cache_dom_element.js    \
scripts/cache_dom_traversal.js  \
scripts/cache_abbreviations.js  \
scripts/cache_color_contrast.js \
scripts/cache_controls.js       \
scripts/cache_headings_landmarks.js \
scripts/cache_images.js         \
scripts/cache_languages.js      \
scripts/cache_links.js          \
scripts/cache_lists.js          \
scripts/cache_nls.js            \
scripts/cache_media.js          \
scripts/cache_style.js          \
scripts/cache_tables.js         \
scripts/cache_util.js           \
scripts/progress_log.js         \
scripts/rules.js                \
scripts/rule_results.js         \
scripts/filtered_cache_item_results.js   \
scripts/filtered_rule_group_results.js  \
scripts/wcag20_ruleset.js       \
scripts/wcag20_nls.js 